// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, run the "Change Firebase Project" command from the command palette.
// Or call the `updateFirebaseProject` function from the Studio API.
export const firebaseConfig = {
  "apiKey": "your-api-key",
  "authDomain": "your-auth-domain",
  "projectId": "your-project-id",
  "storageBucket": "your-storage-bucket",
  "messagingSenderId": "your-messaging-sender-id",
  "appId": "your-app-id"
};
